<?php
class myAppRestResources extends modRestController {

    // Base params
    public $classKey = 'modResource';
    public $defaultSortField = 'id';
    public $defaultSortDirection = 'ASC';

    public function read($id)
    {
        //return parent::read(0); // TODO: Change the autogenerated stub

        $c = $this->getPrimaryKeyCriteria($id);
        $this->object = $this->modx->getObject($this->classKey,$c);
        $objectArray = $this->object->toArray();

        //Получим все тв ресурса
        $tvs = $this->modx->getCollection('modTemplateVarResource', ['contentid' => $id]);

        foreach ($tvs as $tv){

            $objectArray['tv'][] = ['id'=>$tv->id,'name'=>$tv->name,'value'=>$tv->value];
        }


        return $this->success('',$objectArray);
    }

}


